insert into DamageCategoryMaster (code, name) values (100,'Tread Cut Penetration');
insert into DamageCategoryMaster (code, name) values (101,'Tread Cut');
insert into DamageCategoryMaster (code, name) values (102,'Groove Base Crack or Lug Base Crack');
insert into DamageCategoryMaster (code, name) values (103,'Tread Spin Damage');
insert into DamageCategoryMaster (code, name) values (104,'Tread Open Splice');
insert into DamageCategoryMaster (code, name) values (106,'Tread Chunking');
insert into DamageCategoryMaster (code, name) values (108,'Rib/Lug/Block Tear');
insert into DamageCategoryMaster (code, name) values (110,'One Side Shoulder Wear');
insert into DamageCategoryMaster (code, name) values (111,'Both side Shoulder Wear');
insert into DamageCategoryMaster (code, name) values (112,'Centre Wear');
insert into DamageCategoryMaster (code, name) values (113,'Diagonal Wear');
insert into DamageCategoryMaster (code, name) values (114,'River Wear');
insert into DamageCategoryMaster (code, name) values (116,'Heel and Toe Wear');
insert into DamageCategoryMaster (code, name) values (117,'Spot Wear');
insert into DamageCategoryMaster (code, name) values (120,'Rib Punch Wear');
insert into DamageCategoryMaster (code, name) values (121,'Wavy Wear');
insert into DamageCategoryMaster (code, name) values (127,'Feather Edge Wear');
insert into DamageCategoryMaster (code, name) values (130,'Rapid Wear or Worn out');
insert into DamageCategoryMaster (code, name) values (131,'Tread Cut Burst');
insert into DamageCategoryMaster (code, name) values (132,'Impact Break');
insert into DamageCategoryMaster (code, name) values (139,'Tread Leaving Belt');
insert into DamageCategoryMaster (code, name) values (140,'Tread Cut Separation');
insert into DamageCategoryMaster (code, name) values (145,'Tread Deformation');
insert into DamageCategoryMaster (code, name) values (200,'Shoulder Cut-Penetration');
insert into DamageCategoryMaster (code, name) values (201,'Shoulder Cut');
insert into DamageCategoryMaster (code, name) values (203,'Lateral Cracking - Shoulder');
insert into DamageCategoryMaster (code, name) values (206,'Ozone Cracking - Shoulder');
insert into DamageCategoryMaster (code, name) values (207,'Heat Separation at Shoulder');
insert into DamageCategoryMaster (code, name) values (211,'Shoulder Migrate Wire');
insert into DamageCategoryMaster (code, name) values (229,'Radial Split');
insert into DamageCategoryMaster (code, name) values (235,'Belt-Edge Separation');
insert into DamageCategoryMaster (code, name) values (299,'Shoulder Miscellaneous');
insert into DamageCategoryMaster (code, name) values (300,'Sidewall Cut Penetration');
insert into DamageCategoryMaster (code, name) values (301,'Sidewall Cut');
insert into DamageCategoryMaster (code, name) values (303,'Sidewall Flow Crack');
insert into DamageCategoryMaster (code, name) values (304,'Sidewall Open Splice');
insert into DamageCategoryMaster (code, name) values (305,'Radial Cracking');
insert into DamageCategoryMaster (code, name) values (306,'Ozone Cracking - Sidewall');
insert into DamageCategoryMaster (code, name) values (310,'Curbing Abrasion');
insert into DamageCategoryMaster (code, name) values (319,'Foreign Material in Sidewall');
insert into DamageCategoryMaster (code, name) values (321,'Bare at Sidewall');
insert into DamageCategoryMaster (code, name) values (341,'Zipper(CBU - Fatigue Rapture)');
insert into DamageCategoryMaster (code, name) values (344,'Running Flat');
insert into DamageCategoryMaster (code, name) values (345,'Diagonal Cracking');
insert into DamageCategoryMaster (code, name) values (350,'Sidewall Undulation');
insert into DamageCategoryMaster (code, name) values (352,'Separation not-Identified');
insert into DamageCategoryMaster (code, name) values (353,'Sidewall Cut Separation');
insert into DamageCategoryMaster (code, name) values (399,'Sidewall Miscellaneous');
insert into DamageCategoryMaster (code, name) values (400,'Rim digging/Rim Cuts (Bead Damage)');
insert into DamageCategoryMaster (code, name) values (401,'Broken Bead Wire');
insert into DamageCategoryMaster (code, name) values (402,'Bead Deformation');
insert into DamageCategoryMaster (code, name) values (405,'Migrating Bead Wire');
insert into DamageCategoryMaster (code, name) values (410,'Bead Bursting');
insert into DamageCategoryMaster (code, name) values (413,'Burned Beads');
insert into DamageCategoryMaster (code, name) values (430,'Chafer Edge Separation');
insert into DamageCategoryMaster (code, name) values (433,'Ply End Separation');
insert into DamageCategoryMaster (code, name) values (499,'Bead Miscellaneous');
insert into DamageCategoryMaster (code, name) values (504,'Open Inner Splice');
insert into DamageCategoryMaster (code, name) values (506,'Inner Liner Blister');
insert into DamageCategoryMaster (code, name) values (542,'Thin Inner Liner Gauge');
insert into DamageCategoryMaster (code, name) values (708,'Field Improper Repair or Repair Failure');
insert into DamageCategoryMaster (code, name) values (700,'Damage from exposure to Fire/ Heat/ Chemical');
insert into DamageCategoryMaster (code, name) values (155,'Block Punch Wear');
insert into DamageCategoryMaster (code, name) values (203,'Shoulder Scrubbing');
insert into DamageCategoryMaster (code, name) values (310,'Dual Touching');
insert into DamageCategoryMaster (code, name) values (352,'Sidewall Blister');
insert into DamageCategoryMaster (code, name) values (422,'Bead Bulge');
insert into DamageCategoryMaster (code, name) values (499,'Bead Miscellaneous');
insert into DamageCategoryMaster (code, name) values (609,'Ozone Cracking - Tube/Flap');
insert into DamageCategoryMaster (code, name) values (601,'Damage from foreign matter - Tube/Flap');
insert into DamageCategoryMaster (code, name) values (602,'Separation at Valve pad - Tube/Flap');
insert into DamageCategoryMaster (code, name) values (599,'Inner Liner Miscellaneous');
insert into DamageCategoryMaster (code, name) values (531,'Inner Liner Separation');
insert into DamageCategoryMaster (code, name) values (136,'Belt Leaving Belt');
insert into DamageCategoryMaster (code, name) values (135,'Tread Leaving Casing');
insert into DamageCategoryMaster (code, name) values (714,'Factory Repair');
insert into DamageCategoryMaster (code, name) values (603,'Tube Cut by Flap or Tyre - Tube/Flap');
insert into DamageCategoryMaster (code, name) values (604,'Open Splice - Tube/Flap');
insert into DamageCategoryMaster (code, name) values (606,'Pin Holes - Tube/Flap');
insert into DamageCategoryMaster (code, name) values (607,'Valve Broken - Tube/Flap');
insert into DamageCategoryMaster (code, name) values (608,'Damage from Improper mounting and demounting - Tube/Flap');
insert into DamageCategoryMaster (code, name) values (611,'Foreign material in Tube');
insert into DamageCategoryMaster (code, name) values (699,'Tube/Flap Miscellaneous');
insert into DamageCategoryMaster (code, name) values (600,'Puncture from Cutting - Tube/Flap');
insert into DamageCategoryMaster (code, name) values (515,'Pinch Cut');
insert into DamageCategoryMaster (code, name) values (213,'Non Specified Material DT Joint');